extends "res://tests/test_case.gd"

const Session := preload("res://game/finite/build/finite_build_session.gd")
const Loader := preload("res://game/finite/map/finite_map_loader.gd")
const Piece := preload("res://game/finite/build/track_piece.gd")
const Controller := preload("res://game/finite/main/finite_slice_session_controller.gd")
const Alpha := preload("res://tests/fixtures/finite/fp_core_solution_alpha.gd")
const MAP := "res://data/maps/fp_core_proof_01.json"


func run() -> void:
	var session: Variant = Session.new(Loader.load_from_path(MAP))
	assert_true(session.has_method("undo_edit"), "BUILD edits must support exact recovery")
	if not session.has_method("undo_edit"):
		return
	assert_false(session.can_undo(), "fresh session has no past")
	assert_false(session.undo_edit().success, "empty undo is rejected")
	var empty: String = session.layout_signature()
	var switch_piece: Variant = Piece.create(Vector2i(3, 4), &"SWITCH", 0, Vector2i.RIGHT)
	assert_true(session.place_piece(switch_piece).success, "place switch")
	var placed: String = session.layout_signature()
	var price: int = session.current_cost()
	session.rotate_piece(Vector2i(3, 4), 1)
	var rotated: String = session.layout_signature()
	assert_true(session.undo_edit().success, "undo rotation")
	assert_equal(session.layout_signature(), placed, "rotation undo restores geometry and initial exit")
	assert_equal(session.layout_snapshot().piece_at(Vector2i(3, 4)).switch_initial_exit, Vector2i.RIGHT, "switch exit restored")
	assert_equal(session.current_cost(), price, "cost restored")
	session.layout_snapshot().clear()
	assert_equal(session.layout_signature(), placed, "caller copy cannot mutate history")
	session.rotate_piece(Vector2i(3, 4), 4)
	session.place_piece(switch_piece)
	assert_true(session.can_redo(), "no-op and rejected edit preserve redo")
	session.redo_edit()
	assert_equal(session.layout_signature(), rotated, "redo exact rotation")
	session.clear_layout()
	assert_equal(session.current_cost(), 0, "clear refunds all")
	session.undo_edit()
	assert_equal(session.layout_signature(), rotated, "clear recovers whole layout")
	session.remove_piece(Vector2i(3, 4))
	assert_false(session.can_redo(), "changed edit discards redo branch")
	session.undo_edit()
	assert_equal(session.layout_signature(), rotated, "remove recovery")
	session.replace_piece(Piece.create(Vector2i(3, 4), &"CURVE", 0, Vector2i.ZERO))
	session.undo_edit()
	assert_equal(session.layout_signature(), rotated, "replacement recovery")
	session.reset_edit_history()
	assert_false(session.can_undo(), "baseline reset retains board without history")
	assert_false(session.can_redo(), "baseline reset clears future")
	for index in range(140):
		session.rotate_piece(Vector2i(3, 4), 1)
	var undo_count := 0
	while session.can_undo() and undo_count < 200:
		session.undo_edit()
		undo_count += 1
	assert_equal(undo_count, 128, "oldest history is evicted at bounded capacity")
	assert_true(session.replace_layout(Alpha.pieces()).success, "atomic batch valid")
	var solution: String = session.layout_signature()
	var valid: Variant = Piece.create(Vector2i(2, 4), &"STRAIGHT", 0, Vector2i.ZERO)
	var invalid: Variant = Piece.create(Vector2i(-5, -5), &"STRAIGHT", 0, Vector2i.ZERO)
	assert_false(session.replace_layout([valid, invalid]).success, "middle batch failure rejects whole edit")
	assert_equal(session.layout_signature(), solution, "middle failure keeps exact old layout")
	assert_false(session.replace_layout([valid, valid]).success, "duplicate batch cell rejected")
	assert_equal(session.layout_signature(), solution, "duplicate failure keeps exact old layout")
	assert_false(session.replace_layout([Piece.create(Vector2i(-5, -5), &"STRAIGHT", 0, Vector2i.ZERO)]).success, "invalid batch rejected")
	assert_equal(session.layout_signature(), solution, "invalid batch leaves old board intact")
	assert_true(session.begin_run().passed, "known solution starts")
	assert_false(session.can_undo(), "sealed RUN hides history")
	assert_false(session.undo_edit().success, "domain rejects undo in RUN")
	assert_false(session.redo_edit().success, "domain rejects redo in RUN")
	assert_equal(session.layout_signature(), solution, "sealed board unchanged")
	assert_not_equal(solution, empty, "non-empty fixture")
	_controller_contract()


func _controller_contract() -> void:
	var controller: Variant = Controller.new()
	assert_true(controller.initialize(MAP), "controller map")
	controller.request_command(&"BUILD_TOOL", &"STRAIGHT")
	controller.request_command(&"BOARD_CELL", Vector2i(2, 4))
	var placed: String = controller.current_layout_signature()
	assert_true(controller.model().get("undo_enabled", false), "controller publishes available undo")
	controller.request_command(&"UNDO")
	assert_equal(controller.model().get("current_cost"), 0, "controller undo refreshes cost")
	assert_true(controller.model().get("redo_enabled", false), "controller publishes redo")
	controller.request_command(&"REDO")
	assert_equal(controller.current_layout_signature(), placed, "controller redo restores layout")
	assert_true(controller.replace_layout(Alpha.pieces()), "batch replacement")
	controller.request_command(&"UNDO")
	assert_equal(controller.current_layout_signature(), placed, "whole batch is one action")
	controller.request_command(&"REDO")
	assert_true(controller.model().get("start_enabled", false), "restored layout reruns preflight")
	controller.request_command(&"START")
	var sealed: String = controller.current_layout_signature()
	controller.request_command(&"UNDO")
	assert_equal(controller.current_layout_signature(), sealed, "controller cannot rewind RUN")
	controller.request_command(&"EDIT_LAYOUT")
	assert_false(controller.model().get("undo_enabled", true), "Edit establishes fresh baseline")
	assert_equal(controller.current_layout_signature(), sealed, "Edit retains sealed layout")
	assert_true(controller.replace_layout(Alpha.pieces(), true), "starter installation establishes baseline")
	assert_false(controller.model().get("undo_enabled"), "starter cannot be undone")
